name: Commit Lint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
  push:
    branches:
      - develop
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint commits in pull request
        if: github.event_name == 'pull_request'
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.cjs
          failOnWarnings: true

      - name: Lint latest commit on push
        if: github.event_name == 'push'
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.cjs
          commitDepth: 1
          failOnWarnings: true
